# Generated by Django 4.0.4 on 2022-05-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=40, unique=True, verbose_name='사용자 아이디')),
                ('u_pw', models.CharField(max_length=100, verbose_name='사용자 비밀번호')),
                ('u_name', models.CharField(max_length=20, unique=True, verbose_name='사용자 이름')),
                ('u_phone', models.CharField(max_length=40, unique=True, verbose_name='사용자 번호')),
                ('u_register_date', models.DateTimeField(auto_now_add=True, verbose_name='사용자 계정 생성 시간')),
            ],
            options={
                'verbose_name': '유저 정보',
                'verbose_name_plural': '유저 정보',
                'db_table': 'user',
            },
        ),
    ]
