# Generated by Django 4.0.4 on 2022-06-14 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('write_date', models.DateTimeField(auto_now_add=True, verbose_name='작성 날짜')),
                ('board_category', models.CharField(default='Python', max_length=50, verbose_name='게시판 카테고리')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='최근 수정된 날짜')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.user', verbose_name='글 작성자')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판',
                'db_table': 'board',
            },
        ),
    ]
