# Generated by Django 4.0.4 on 2022-06-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinboard',
            name='board_category',
            field=models.CharField(default='Free', max_length=50, verbose_name='게시판 카테고리'),
        ),
    ]
