# Generated by Django 4.0.4 on 2022-06-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboard', '0002_alter_bulletinboard_board_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bulletinboard',
            table='bulletinboard',
        ),
    ]
